language: python

python:
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy3"
os:
  - linux
  # Python on OSX doesn't work as per https://github.com/travis-ci/travis-ci/issues/2312
  #- osx

sudo: false
install: pip install tox-travis
script: tox
