language: python

python:
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy3"
os:
  - linux
  - osx

sudo: false
install:
  - pip install -e .
  - pip install -r requirements-test.txt
script: py.test
