# gisht :: Homebrew formula definition
# AUTOGENERATED BY ./tools/release.sh -- DO NOT EDIT!

class Gisht < Formula
  homepage "http://github.com/Xion/gisht"
  url "https://pypi.python.org/packages/source/g/gisht/gisht-0.5.tar.gz"
  sha256 "64d13a7dd0e07289b50ded5e1b45b6af6c8d32c40ef5dc4408cb994d7b2e4a7b"

  depends_on :python if MacOS.version <= :snow_leopard

  resource "argcomplete" do
    url "https://pypi.python.org/packages/source/a/argcomplete/argcomplete-0.8.4.tar.gz"
    sha256 "925587268e509a8a1cb80c5d3f7190547de2990b7feb46993530a691a14e9255"
  end

  resource "enum34" do
    url "https://pypi.python.org/packages/source/e/enum34/enum34-1.0.4.tar.gz"
    sha256 "d3c19f26a6a34629c18c775f59dfc5dd595764c722b57a2da56ebfb69b94e447"
  end

  resource "envoy" do
    url "https://pypi.python.org/packages/source/e/envoy/envoy-0.0.3.tar.gz"
    sha256 "22b02009cfda2cf2cdb94a75a15ac3fd910aea8685c53e8e03715c7e9d8e8bde"
  end

  resource "furl" do
    url "https://pypi.python.org/packages/source/f/furl/furl-0.4.7.tar.gz"
    sha256 "6799578d59ef9a31207a7e8b110d892db9e72da51dc608716ce1d6e478afa268"
  end

  resource "hammock" do
    url "https://pypi.python.org/packages/source/h/hammock/hammock-0.2.4.tar.gz"
    sha256 "a535f085b7c1c10f675761a8bc8853618cbc66f80d71491eb2486e53ce1f8730"
  end

  resource "orderedmultidict" do
    url "https://pypi.python.org/packages/source/o/orderedmultidict/orderedmultidict-0.7.5.tar.gz"
    sha256 "8a76df859dfe92cf2c3a113f7a2103b360b1168cd1e6d7fcdfcf58b7bfe294e8"
  end

  resource "pathlib" do
    url "https://pypi.python.org/packages/source/p/pathlib/pathlib-1.0.1.tar.gz"
    sha256 "6940718dfc3eff4258203ad5021090933e5c04707d5ca8cc9e73c94a7894ea9f"
  end

  resource "requests" do
    url "https://pypi.python.org/packages/source/r/requests/requests-2.5.1.tar.gz"
    sha256 "7b7735efd3b1e2323dc9fcef060b380d05f5f18bd0f247f5e9e74a628279de66"
  end

  resource "six" do
    url "https://pypi.python.org/packages/source/s/six/six-1.8.0.tar.gz"
    sha256 "047bbbba41bac37c444c75ddfdf0573dd6e2f1fbd824e6247bb26fa7d8fa3830"
  end

  resource "tabulate" do
    url "https://pypi.python.org/packages/source/t/tabulate/tabulate-0.7.3.tar.gz"
    sha256 "8a59a61ed6ddfdb009f15917e0f006cc5842f9daa72c519593b7a095e645532a"
  end

  def install
    ENV.prepend_create_path "PYTHONPATH", libexec/"vendor/lib/python2.7/site-packages"
    %w[argcomplete enum34 envoy furl hammock orderedmultidict pathlib requests six tabulate].each do |r|
      resource(r).stage do
        system "python", *Language::Python.setup_install_args(libexec/"vendor")
      end
    end

    ENV.prepend_create_path "PYTHONPATH", libexec/"lib/python2.7/site-packages"
    system "python", *Language::Python.setup_install_args(libexec)

    bin.install Dir[libexec/"bin/*"]
    bin.env_script_all_files(libexec/"bin", :PYTHONPATH => ENV["PYTHONPATH"])
  end
end
