#!/bin/sh

# Release automation script

set -e


HB_FORMULA='gisht.rb'


main() {
    create_homebrew_formula
}


create_homebrew_formula() {
    local tmpfile="/tmp/$HB_FORMULA"
    rm -f "$tmpfile"

    cat << EOF >"$tmpfile"
# gisht :: Homebrew formula definition
# AUTOGENERATED BY ./tools/release.sh -- DO NOT EDIT!

EOF

    poet --formula gisht >>"$tmpfile"
    mv -f "$tmpfile" "./$HB_FORMULA"
}


main "$@"
